// ParaCL runtime library (pclrt)
//
// Defines the extern "C" symbols that the generated LLVM IR calls:
//   __pcl_print(int)  -- implements `print <expr>`
//   __pcl_scan()      -- implements `?` (read from stdin)
//   main()            -- C entry point; calls __pcl_start() generated by compiler
//

#include <cstdlib>
#include <iostream>

extern "C" void __pcl_start();

extern "C" void __pcl_print (int n)
{
    std::cout << n << "\n";
}

extern "C" int __pcl_scan()
{
    int n = 0;
    if (!(std::cin >> n))
    {
        std::cerr << "Runtime error: failed to read integer from stdin\n";
        std::exit (1);
    }

    return n;
}

int main()
{
    __pcl_start();
}
